const courses=[['Digital Marketing','Social media, content & campaign fundamentals.','✦'],['Graphic Design','Design essentials for business and branding.','◇'],['Video Editing','Create engaging videos for social platforms.','▶'],['Freelancing','Build a profile and understand digital work.','↗'],['Facebook Marketing','Learn practical page and ad strategies.','f'],['E-Commerce','Explore online selling and store basics.','◆'],['AI for Business','Use modern AI tools for productivity.','AI'],['Content Creation','Plan, write and publish useful content.','✎']];
document.getElementById('courseGrid').innerHTML=courses.map(c=>`<article class="course"><div class="course-cover">${c[2]}</div><div class="course-body"><h3>${c[0]}</h3><p>${c[1]}</p><button class="btn btn-outline" onclick="alert('Course preview: ${c[0]}')">View Course →</button></div></article>`).join('');
const categories=[['👗','ফ্রক তৈরির কাজ','Frock Making'],['🪡','নকশিকাঁথার কাজ','Nakshi Kantha'],['🌸','ফুলের গহনা তৈরির কাজ','Flower Jewelry'],['💍','চুড়ি বানানোর কাজ','Bangle Making'],['✂️','টেইলারিং কাজ','Tailoring'],['🕯️','Candle বানানোর কাজ','Candle Making'],['🧶','কুশিকাঁটার কাজ','Crochet'],['🎨','পেইন্টিং — শাড়ি, পাঞ্জাবি ও ওড়না','Fabric Painting'],['✨','জামায় পুঁতি বসানোর কাজ','Bead Work']];
const catGrid=document.getElementById('categoryGrid');let selected=new Set(JSON.parse(localStorage.getItem('we_categories')||'[]'));
catGrid.innerHTML=categories.map((c,i)=>`<button class="category ${selected.has(i)?'active':''}" data-index="${i}"><span class="emoji">${c[0]}</span><span><strong>${c[1]}</strong><small>(${c[2]})</small></span><span class="check">${selected.has(i)?'✓':''}</span></button>`).join('');
catGrid.querySelectorAll('.category').forEach(btn=>btn.onclick=()=>{const i=+btn.dataset.index;if(selected.has(i))selected.delete(i);else selected.add(i);localStorage.setItem('we_categories',JSON.stringify([...selected]));btn.classList.toggle('active');btn.querySelector('.check').textContent=selected.has(i)?'✓':''});
document.getElementById('selectAllBtn').onclick=()=>{selected=new Set(categories.map((_,i)=>i));localStorage.setItem('we_categories',JSON.stringify([...selected]));catGrid.querySelectorAll('.category').forEach((b,i)=>{b.classList.add('active');b.querySelector('.check').textContent='✓'})};
const drawer=document.getElementById('drawer'),backdrop=document.getElementById('backdrop');document.getElementById('menuBtn').onclick=()=>{drawer.classList.add('open');backdrop.classList.add('show')};document.getElementById('drawerClose').onclick=closeDrawer;backdrop.onclick=closeDrawer;document.querySelectorAll('.drawer a').forEach(a=>a.onclick=closeDrawer);function closeDrawer(){drawer.classList.remove('open');backdrop.classList.remove('show')}
function openModal(id){document.getElementById(id).classList.add('show');document.getElementById(id).setAttribute('aria-hidden','false')}function closeModals(){document.querySelectorAll('.modal').forEach(m=>{m.classList.remove('show');m.setAttribute('aria-hidden','true')})}document.querySelectorAll('[data-open]').forEach(b=>b.onclick=e=>{e.preventDefault();openModal(b.dataset.open)});document.querySelectorAll('.modal-close').forEach(b=>b.onclick=closeModals);document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModals()});
let profile=JSON.parse(localStorage.getItem('we_profile')||'null')||{name:'Your Name',email:'yourname@gmail.com',phone:'+880 1XXXXXXXXX',id:'WE-2026-0001',referral:'WE-REF0001',joined:'29 Sep 2026'};
function renderProfile(){[['profileName',profile.name],['pName',profile.name],['pId',profile.id],['pEmail',profile.email],['pReferral',profile.referral],['pPhone',profile.phone],['pJoined',profile.joined],['dName',profile.name],['dId',profile.id],['dEmail',profile.email],['dPhone',profile.phone],['dReferral',profile.referral],['demoStudentId',profile.id],['demoReferral',profile.referral]].forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.textContent=v})}renderProfile();
function openEdit(){document.getElementById('fName').value=profile.name;document.getElementById('fEmail').value=profile.email;document.getElementById('fPhone').value=profile.phone;openModal('editModal')}document.getElementById('editProfileBtn').onclick=openEdit;document.getElementById('editProfileBtn2').onclick=openEdit;
document.getElementById('profileForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);profile.name=f.get('name');profile.email=f.get('email');profile.phone=f.get('phone');localStorage.setItem('we_profile',JSON.stringify(profile));renderProfile();const r=document.getElementById('profileResult');r.className='result show';r.textContent='Profile updated successfully.';setTimeout(closeModals,700)};
function setPhoto(src){document.getElementById('profileAvatar').src=src;document.getElementById('profilePreview').src=src}function choosePhoto(){document.getElementById('photoInput').click()}document.getElementById('uploadPhotoBtn').onclick=choosePhoto;document.getElementById('changePhotoBtn').onclick=choosePhoto;document.getElementById('photoInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{setPhoto(reader.result);localStorage.setItem('we_profile_photo',reader.result)};reader.readAsDataURL(file)};const savedPhoto=localStorage.getItem('we_profile_photo');if(savedPhoto)setPhoto(savedPhoto);
document.getElementById('downloadPhotoBtn').onclick=()=>{const img=document.getElementById('profilePreview');const canvas=document.createElement('canvas'),size=Math.max(img.naturalWidth,img.naturalHeight,600);canvas.width=600;canvas.height=600;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,600,600);const scale=Math.min(600/img.naturalWidth,600/img.naturalHeight);const w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.drawImage(img,(600-w)/2,(600-h)/2,w,h);const a=document.createElement('a');a.href=canvas.toDataURL('image/jpeg',.92);a.download=(profile.name||'profile').replace(/\s+/g,'-').toLowerCase()+'-profile.jpg';a.click()};
document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const t=document.getElementById(b.dataset.copy).textContent;try{await navigator.clipboard.writeText(t);b.textContent='Copied ✓';setTimeout(()=>b.textContent='Copy',900)}catch{alert(t)}});document.getElementById('copyDemo').onclick=async()=>{try{await navigator.clipboard.writeText(profile.referral);document.getElementById('copyDemo').textContent='Copied ✓';setTimeout(()=>document.getElementById('copyDemo').textContent='Copy Referral Code',900)}catch{alert(profile.referral)}};
function nextId(){const n=Number(localStorage.getItem('we_next_id')||1);localStorage.setItem('we_next_id',String(n+1));return `WE-2026-${String(n).padStart(4,'0')}`}function saveStudent(s){localStorage.setItem('we_student_'+s.id,JSON.stringify(s));localStorage.setItem('we_last_student',s.id)}
document.getElementById('registerForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),id=nextId(),ref='WE-REF'+id.split('-').pop();const s={id,referral:ref,name:f.get('name'),email:f.get('email'),phone:f.get('phone'),referredBy:f.get('referral')||null,createdAt:new Date().toISOString()};saveStudent(s);profile={...profile,name:s.name,email:s.email,phone:s.phone,id:s.id,referral:s.referral,joined:new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})};localStorage.setItem('we_profile',JSON.stringify(profile));renderProfile();const r=document.getElementById('registerResult');r.className='result show';r.innerHTML=`<b>Account created!</b><br>Student ID: <strong>${id}</strong><br>Referral Code: <strong>${ref}</strong>`;e.target.reset()};
document.getElementById('loginForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),key=String(f.get('id')).trim(),id=key.startsWith('WE-')?key:localStorage.getItem('we_last_student'),s=localStorage.getItem('we_student_'+id),r=document.getElementById('loginResult');r.className='result show';r.innerHTML=s?`Welcome back, <b>${JSON.parse(s).name}</b>!<br>Student ID: <strong>${id}</strong>`:'Demo account not found. Create an account first.'};
