const skills=[['👗','ফ্রক তৈরির কাজ','Frock Making'],['🪡','নকশিকাঁথার কাজ','Nakshi Kantha'],['🌸','ফুলের গহনা তৈরির কাজ','Flower Jewelry'],['💍','চুড়ি বানানোর কাজ','Bangle Making'],['✂️','টেইলারিং কাজ','Tailoring'],['🕯️','Candle বানানোর কাজ','Candle Making'],['🧶','কুশিকাঁটার কাজ','Crochet'],['🎨','Painting — শাড়ি, পাঞ্জাবি ও ওড়না','Fabric Painting'],['✨','জামায় পুঁতি বসানোর কাজ','Bead Work']];
const $=id=>document.getElementById(id); const modal=$('modal'),dash=$('dash');
let selected=JSON.parse(localStorage.getItem('weSkills')||'[]');
let accounts=JSON.parse(localStorage.getItem('weAccounts')||'[]');
let current=JSON.parse(localStorage.getItem('weCurrent')||'null');
function saveAccounts(){localStorage.setItem('weAccounts',JSON.stringify(accounts));}
function render(id,click=false){$(id).innerHTML=skills.map((s,i)=>`<div class="skill ${selected.includes(i)?'sel':''}" data-i="${i}"><div class="skill-icon">${s[0]}</div><div><h3>${s[1]}</h3><small>${s[2]}</small></div>${click?'<div class="check">✓</div>':''}</div>`).join(''); if(click)$(id).querySelectorAll('.skill').forEach(x=>x.onclick=()=>{let i=+x.dataset.i;selected=selected.includes(i)?selected.filter(v=>v!==i):[...selected,i];localStorage.setItem('weSkills',JSON.stringify(selected));if(current){current.skills=selected;saveCurrent();}render('dashSkills',true)})}
function saveCurrent(){localStorage.setItem('weCurrent',JSON.stringify(current));accounts=accounts.map(a=>a.uid===current.uid?current:a);saveAccounts();}
function open(mode='login'){modal.classList.add('show');$('loginPanel').style.display=mode==='login'?'block':'none';$('signupPanel').style.display=mode==='signup'?'block':'none';}
function close(){modal.classList.remove('show')}
function makeId(){return 'WE-'+String(Math.floor(1000+Math.random()*9000));}
function makeReferral(name){return (name.replace(/[^a-zA-Z]/g,'').slice(0,5).toUpperCase()||'WOMEN')+Math.floor(100+Math.random()*900)}
function updateProfile(){if(!current)return; $('pName').textContent=current.name;$('pUid').textContent=current.uid;$('pGmail').textContent=current.gmail;$('pPhone').textContent=current.phone;$('pReferral').textContent=current.referral;$('pJoined').textContent=current.joined;$('pTitle').textContent=current.name;$('pSub').textContent='Women Entrepreneur • Member'; if(current.photo)$('avatar').src=current.photo; else $('avatar').src='assets/logo.png'; selected=current.skills||[];render('dashSkills',true);}
['login1','login2','footerLogin'].forEach(id=>$(id).onclick=()=>open('login'));$('signup').onclick=()=>open('signup');$('close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};
$('form').onsubmit=e=>{e.preventDefault();const uid=$('uid').value.trim(),pw=$('pw').value;const acc=accounts.find(a=>a.uid.toLowerCase()===uid.toLowerCase()&&a.password===pw);if(!acc){alert('User ID অথবা Password ভুল। আগে Sign Up করে account তৈরি করুন।');return;}current=acc;selected=current.skills||[];localStorage.setItem('weCurrent',JSON.stringify(current));close();updateProfile();show();};
$('signupForm').onsubmit=e=>{e.preventDefault();const name=$('regName').value.trim(),gmail=$('regGmail').value.trim(),phone=$('regPhone').value.trim(),pw=$('regPw').value;if(accounts.some(a=>a.gmail.toLowerCase()===gmail.toLowerCase())){alert('এই Gmail দিয়ে আগে থেকেই account আছে। Login করুন।');return;}const acc={uid:makeId(),name,gmail,phone,password:pw,referral:makeReferral(name),joined:new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),photo:'',skills:[]};accounts.push(acc);saveAccounts();current=acc;selected=[];localStorage.setItem('weCurrent',JSON.stringify(current));close();updateProfile();show();alert(`Registration সফল!\nYour User ID: ${acc.uid}\nReferral Code: ${acc.referral}`);};
function show(){dash.classList.add('show');document.body.style.overflow='hidden';scrollTo(0,0);updateProfile()}function hide(){dash.classList.remove('show');document.body.style.overflow='';scrollTo(0,0)}$('homeBtn').onclick=hide;$('logout').onclick=()=>{localStorage.removeItem('weCurrent');current=null;hide()};
$('all').onclick=()=>{selected=selected.length===skills.length?[]:skills.map((_,i)=>i);if(current){current.skills=selected;saveCurrent();}render('dashSkills',true)};
$('edit').onclick=()=>{if(!current)return;const name=prompt('Name',current.name);if(name===null)return;const gmail=prompt('Gmail',current.gmail);if(gmail===null)return;const phone=prompt('Phone',current.phone);if(phone===null)return;current.name=name.trim()||current.name;current.gmail=gmail.trim()||current.gmail;current.phone=phone.trim()||current.phone;saveCurrent();updateProfile();};
$('photo').onchange=e=>{let f=e.target.files[0];if(!f||!current)return;let r=new FileReader();r.onload=()=>{current.photo=r.result;saveCurrent();$('avatar').src=r.result};r.readAsDataURL(f)};
$('jpg').onclick=()=>{if(!current)return;let c=document.createElement('canvas');c.width=1200;c.height=760;let x=c.getContext('2d');let g=x.createLinearGradient(0,0,1200,760);g.addColorStop(0,'#17113e');g.addColorStop(1,'#8b327b');x.fillStyle=g;x.fillRect(0,0,1200,760);x.fillStyle='#fff';x.font='800 52px Arial';x.fillText('WOMEN ENTREPRENEUR',80,100);x.font='800 45px Arial';x.fillText(current.name,380,270);x.font='24px Arial';x.fillStyle='#b8c1db';x.fillText('User ID: '+current.uid,380,315);x.fillText('Gmail: '+current.gmail,380,355);x.fillText('Phone: '+current.phone,380,395);x.fillText('Referral: '+current.referral,380,435);x.fillText('Joined: '+current.joined,380,475);x.fillStyle='#62eaff';x.font='700 26px Arial';x.fillText('My Work / Skills',80,540);x.fillStyle='#fff';x.font='21px Arial';skills.filter((_,i)=>selected.includes(i)).forEach((s,i)=>x.fillText(s[0]+' '+s[2],80+(i%3)*330,590+Math.floor(i/3)*45));let a=document.createElement('a');a.download=(current.name||'Profile').replace(/\s+/g,'-')+'-Profile.jpg';a.href=c.toDataURL('image/jpeg',.95);a.click()};
$('lang').onclick=$('lang2').onclick=()=>{document.querySelectorAll('[data-bn]').forEach(e=>{let old=e.textContent;e.textContent=e.textContent===e.dataset.bn?(e.dataset.en||old):e.dataset.bn});$('lang').textContent=$('lang').textContent==='বাংলা'?'English':'বাংলা';$('lang2').textContent=$('lang2').textContent==='বাংলা'?'English':'বাংলা'};
render('skillsGrid');if(current)updateProfile();
